name: UnitTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: UnitTest
   
    strategy:
      matrix:
        php-version:
          - "7.2"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: "Install PHP with extensions"
      uses: "shivammathur/setup-php@v2"
      with:
        coverage: "none"
        extensions: "mbstring"
        ini-values: "memory_limit=-1"
        php-version: "${{ matrix.php-version }}"
        
    - name: Get composer cache directory
      id: "composer-cache"
      run: "echo \"::set-output name=dir::$(composer config cache-files-dir)\""
      
    - name: Cache dependencies installed with composer
      uses: "actions/cache@v1"
      with:
        path: "${{ steps.composer-cache.outputs.dir }}"
        key: "php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}"
        restore-keys: "php-${{ matrix.php-version }}-composer-"

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: Run test suite
      run: composer run-script test

